#!/usr/bin/env python3
"""
House style pass: remove em dashes and en dashes from visible copy across the site.

Kept on purpose (structural, not prose):
  - the page-title separator, as in `Name — Tagline | LaunchFree.io`
  - the brand lockup `LaunchFree.io — The Runway`

Everything else is rewritten by rule:
  - a short label followed by a dash becomes a colon      "Headline — what it is"  -> "Headline: what it is"
  - a dash before an attribution name is dropped          "— Julie James"          -> "Julie James"
  - a numeric range keeps a plain hyphen                  "$5–$7"                  -> "$5-$7"
  - anything else becomes a comma                         "permanently — indexed"  -> "permanently, indexed"

Run from the repo root:

    python3 docs/fix_house_style.py            # dry run, prints every proposed change
    python3 docs/fix_house_style.py --write    # apply

Never touches git.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if not os.path.exists(os.path.join(ROOT, "listings.json")):
    ROOT = os.getcwd()
WRITE = "--write" in sys.argv
DASH = "[–—]"

KEEP = [
    # the brand lockup, with or without markup inside it
    re.compile(r"LaunchFree(?:<[^>]+>|\.io|\s)*[–—]\s*The Runway"),
    re.compile(r"<title>[^<]*</title>"),
    re.compile(r'<meta[^>]*content="[^"]*"[^>]*>'),
    re.compile(r"[–—] The Runway \| LaunchFree\.io"),
]

files = []
# listings/ is not included: those pages are generated by docs/rebuild_listings.py, which
# applies the same rules at build time. This pass is for the hand-written pages only.
for pat in ("*.html", "radar/*.html", "research/*.html"):
    files += sorted(glob.glob(os.path.join(ROOT, pat)))

changes = 0
touched = []

for path in files:
    src = open(path, encoding="utf-8").read()
    # protect regions we never touch
    holds = {}

    def hold(m):
        k = "\x00HOLD%d\x00" % len(holds)
        holds[k] = m.group(0)
        return k

    s = src
    s = re.sub(r"<script.*?</script>", hold, s, flags=re.S)
    s = re.sub(r"<style.*?</style>", hold, s, flags=re.S)
    s = re.sub(r"<!--.*?-->", hold, s, flags=re.S)
    for k in KEEP:
        s = k.sub(hold, s)

    def label_colon(m):
        label, tags = m.group(1), m.group(2)
        words = label.strip().split()
        # only a genuine short label, not the tail of a sentence
        if len(words) > 5 or label.strip().endswith((".", ",", ":", ";")):
            return "%s%s, " % (label, tags)
        return "%s%s: " % (label.rstrip(), tags)

    out = s
    # numeric range keeps a hyphen
    out = re.sub(r"(?<=[\d$])\s*%s\s*(?=[\d$])" % DASH, "-", out)
    # attribution before a name, even with markup in between
    out = re.sub(r"%s\s*((?:<[^>]+>\s*)*)(?=(?:Julie James|The Runway team))" % DASH, r"\1", out)
    # a short label that is the whole text node becomes a colon
    out = re.sub(r"(?<=>)(\s*[A-Z][^<>]{0,60}?)((?:\s*</[a-z]+>)*)\s*%s\s*" % DASH,
                 label_colon, out)
    # everything else becomes a comma
    out = re.sub(r"\s*%s\s*" % DASH, ", ", out)
    out = re.sub(r",\s*,", ",", out)
    out = re.sub(r"\s+,", ",", out)
    out = re.sub(r",(\s*</)", r"\1", out)

    for _ in range(6):  # holds can nest, so restore until nothing is left
        for k, v in holds.items():
            out = out.replace(k, v)
        if "\x00HOLD" not in out:
            break
    assert "\x00HOLD" not in out, "unrestored placeholder in %s" % path

    if out != src:
        n = len(re.findall(DASH, re.sub(r"<[^>]+>", " ", src))) - \
            len(re.findall(DASH, re.sub(r"<[^>]+>", " ", out)))
        changes += max(n, 0)
        touched.append((os.path.relpath(path, ROOT), max(n, 0)))
        if WRITE:
            open(path, "w", encoding="utf-8").write(out)
        else:
            plain_old = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", src))
            plain_new = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", out))
            for m in re.finditer(DASH, plain_old):
                print("  %-40s ...%s" % (os.path.relpath(path, ROOT),
                                         plain_old[max(0, m.start() - 55):m.start() + 55].strip()))

print("\n%d dashes in %d files %s" % (changes, len(touched), "rewritten" if WRITE else "would change"))
for f, n in touched:
    print("  %-55s %d" % (f, n))
if not WRITE:
    print("Dry run. Re-run with --write to apply.")
